### ISSUE TITLE
GitHub-Autolink Spam on large Repositories

### ISSUE THREAD

**Issue by timkante** [Staffbase/autodev-action#20]
## Summary

On bigger repositories, with many dev'ed PRs in parallel, the status comments of this action link all of them as intended. 
However this leads to a GitHub annotating each of the PRs with all the other PRs. This is due to GitHub autolinker recognizing the PR-Links and annotating the linked PR with something like "This PR was mentioned in PR".  

### Feature Suggestion

The Status Comments are nice and give a good feedback of what the action produced, so disabling the comments is not the optimal Solution here.
We should provide a way to reduce the AutoLink spam without giving away the comments nicities.

### Possible Implementation

I was thinking about some kind of templating we can provide for the action. So we can give the Users the ability to Structure the comments themselves.
This is the way for example [release-drafter/release-drafter](https://github.com/release-drafter/release-drafter) handles dynamic outputs.
So we use some kind of templating Engine (e.g. go-template) and provide the users a documentation of what parameters we compile into the Template. This way they can leave out what they want to leave out, or can even use handmade messages for the Comments ✨ 🎨

**Comment by aksdb** [comment]
Also consider just updating the existing comment instead of adding new ones. The old ones don't matter anyway, don't they?

**Comment by flaxel** [comment]
Or we can also use labels as we are doing it currently in the backend. 👍
